const mongoose = require('mongoose');
const Booking = require('../models/booking.model');
const config = require('../config/config');

const bookings1 = [
    {
        fromLocation: 'T1, KIAL',
        toLocation: 'Brigade Cornerstone, Varthur',
        dateTime: new Date('2025-01-10T20:00:00'), // 8:00 PM
        status: 'completed',
        name: 'Nikhil Ghodke',
        mobile: '8087272290',
        notes: '',
        driverName: 'Chandan Kumar',
        tripCost: 599,
    },
    {
        fromLocation: 'PLH, Varthur',
        toLocation: 'T2, KIAL',
        dateTime: new Date('2025-01-11T10:00:00'), // 10:00 AM
        status: 'completed',
        name: 'Anuroop',
        mobile: '9650285513',
        notes: '',
        driverName: 'Jabed Laskar',
        tripCost: 599,
    },
    {
        fromLocation: 'T1, KIAL',
        toLocation: 'Meenakshi Temple, Bannerghata Road',
        dateTime: new Date('2025-01-11T13:00:00'), // 1:00 PM
        status: 'completed',
        name: 'Abhra Dutta',
        mobile: '7618785409',
        notes: '',
        driverName: 'Jabed Laskar',
        tripCost: 725,
    },
    {
        fromLocation: 'Godrej United, Whitefield',
        toLocation: 'T1, KIAL',
        dateTime: new Date('2025-01-11T15:00:00'), // 3:00 PM
        status: 'completed',
        name: 'Bala',
        mobile: '8800788660',
        notes: '',
        driverName: 'Chandan Kumar',
        tripCost: 600,
    },
    {
        fromLocation: 'Brigade Utopia, Whitefield',
        toLocation: 'T1, KIAL',
        dateTime: new Date('2025-01-12T05:00:00'), // 5:00 AM
        status: 'completed',
        name: 'Vineet Ranjan',
        mobile: '8880893475',
        notes: '',
        driverName: 'Chandan Kumar',
        tripCost: 599,
    },
    {
        fromLocation: 'T1, KIAL',
        toLocation: 'Suncity Apartments, Bellandur',
        dateTime: new Date('2025-01-12T11:00:00'), // 11:00 AM
        status: 'completed',
        name: 'Ajinkya Shinkar',
        mobile: '9096160486',
        notes: '',
        driverName: 'Chandan Kumar',
        tripCost: 599,
    },
    {
        fromLocation: 'Mahaveer Ranches, Hosa Road',
        toLocation: 'T1, KIAL',
        dateTime: new Date('2025-01-12T12:30:00'), // 12:30 PM
        status: 'completed',
        name: 'Richa Sinha',
        mobile: '9155524079',
        notes: '',
        driverName: 'Chandan Kumar',
        tripCost: 599,
    },
    {
        "fromLocation": "Mahaveer Ranches",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-13 00:00:00T08:00:00')",
        "status": "completed",
        "name": "Tarun Behari",
        "mobile": "9818413183",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 599
    },
    {
        "fromLocation": "T1, KIAL",
        "toLocation": "Prestige Silver Oak, Whitefield",
        "dateTime": "new Date('2025-01-13 00:00:00T17:00:00')",
        "status": "completed",
        "name": "Rashmi Bharti",
        "mobile": "7039745737",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 599
    },
    {
        "fromLocation": "T1, KIAL",
        "toLocation": "Varthur",
        "dateTime": "new Date('2025-01-13 00:00:00T22:00:00')",
        "status": "completed",
        "name": "Virendra Sahdev",
        "mobile": "9342735454",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 725
    },
    {
        "fromLocation": "Costa Coral Reef, Hosa Road",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-14 00:00:00T05:00:00')",
        "status": "completed",
        "name": "Rajnish",
        "mobile": "6364802303",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 599
    },
    {
        "fromLocation": "T1, KIAL",
        "toLocation": "PLH, Varthur",
        "dateTime": "new Date('2025-01-14 00:00:00T08:30:00')",
        "status": "completed",
        "name": "Shikha ",
        "mobile": "9575379898",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 599
    },
    {
        "fromLocation": "Mahaveer Ranches",
        "toLocation": "T1 KIAL",
        "dateTime": "new Date('2025-01-14 00:00:00T09:00:00')",
        "status": "completed",
        "name": "Pradeep",
        "mobile": "9900032244",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 725
    },
    {
        "fromLocation": "T1 KIAL",
        "toLocation": "Nagarjuna Greenridge, HSR ",
        "dateTime": "new Date('2025-01-14 00:00:00T10:30:00')",
        "status": "completed",
        "name": "SSC",
        "mobile": "7471116077",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 599
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-14 00:00:00T11:00:00')",
        "status": "completed",
        "name": "Dinesh Jain",
        "mobile": "9999662952",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 599
    },
    {
        "fromLocation": "Mahaveer Ranches",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-14 00:00:00T12:30:00')",
        "status": "Empty",
        "name": "Sakshi Rohilla",
        "mobile": "8136902522",
        "notes": "Didn't got the confirmation from customer",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "Mana Foresta, Wipro Gate, Sarjapur Road",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-14 00:00:00T15:30:00')",
        "status": "completed",
        "name": "Ashish",
        "mobile": "9545726644",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 599
    },
    {
        "fromLocation": "T1, KIAL",
        "toLocation": "Suncity Apartment, Bellandur",
        "dateTime": "new Date('2025-01-15 00:00:00T01:00:00')",
        "status": "completed",
        "name": "Chaitanya Mittal",
        "mobile": "9582288062",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 599
    },
    {
        "fromLocation": "Mahaveer Ranches",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-15 00:00:00T02:00:00')",
        "status": "completed",
        "name": "Nayanjyoti Bhagwati",
        "mobile": "9742165274",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 725
    },
    {
        "fromLocation": "Godrej Woodsman Estate, Hebbal",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-15 00:00:00T04:40:00')",
        "status": "completed",
        "name": "Rizwan",
        "mobile": "9961025666",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 750
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-15 00:00:00T07:00:00')",
        "status": "completed",
        "name": "Ansh",
        "mobile": "9036124202",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 550
    },
    {
        "fromLocation": "T1, KIAL",
        "toLocation": "PLH",
        "dateTime": "new Date('2025-01-15 00:00:00T09:00:00')",
        "status": "completed",
        "name": "Ansh",
        "mobile": "9036124202",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 550
    },
    {
        "fromLocation": "T1 KIAL",
        "toLocation": "PLH",
        "dateTime": "new Date('2025-01-15 00:00:00T23:30:00')",
        "status": "completed",
        "name": "Nagaveni",
        "mobile": "9731590200",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 599
    },
    {
        "fromLocation": "Mahaveer Maple, Kundanahalli",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-15 00:00:00T23:45:00')",
        "status": "completed",
        "name": "Abik Halder",
        "mobile": "9432750536",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },
    {
        "fromLocation": "ND Passion Apartment, Haralur",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-15 00:00:00T23:45:00')",
        "status": "completed",
        "name": "Abik Halder",
        "mobile": "9432750536",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 599
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-16 00:00:00T00:30:00')",
        "status": "completed",
        "name": "DA",
        "mobile": "9686529495",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 599
    },
    {
        "fromLocation": "Kalakunte Education School, Ramamohanapuram",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-16 00:00:00T02:00:00')",
        "status": "cancelled",
        "name": "Jay Megotia",
        "mobile": "8609491889",
        "notes": "Dont want to pay toll tax as extra",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "MDM Paradise",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-16 00:00:00T04:00:00')",
        "status": "completed",
        "name": "Achraj Revoo",
        "mobile": "7740920141",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 725
    },
    {
        "fromLocation": "Suncity Apartment, Bellandur",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-16 00:00:00T08:30:00')",
        "status": "completed",
        "name": "Chaitanya Mittal",
        "mobile": "9582288062",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 600
    },
    {
        "fromLocation": "Brigade Cornerstone, Varthur",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-16 00:00:00T10:00:00')",
        "status": "completed",
        "name": "Nikhil Ghodke",
        "mobile": "8087272290",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 599
    },
    {
        "fromLocation": "GR Sunshine, Carmelaram",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-16 00:00:00T11:00:00')",
        "status": "Empty",
        "name": "Atul",
        "mobile": "9741296062",
        "notes": "No cabs available for pick-up",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "Ebenezer Church, Electronic City",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-16 00:00:00T16:00:00')",
        "status": "completed",
        "name": "Adarsh Hamirwasia",
        "mobile": "8084524848",
        "notes": "Take ORR. Collect 825.",
        "driverName": "Jabed Laskar",
        "tripCost": 825
    },
    {
        "fromLocation": "Lisha Vistara, Green Glen Layout",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-16 00:00:00T19:00:00')",
        "status": "completed",
        "name": null,
        "mobile": "9958872341",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 600
    },
    {
        "fromLocation": "T2 KIAL",
        "toLocation": "Mantri Astra, Hennur",
        "dateTime": "new Date('2025-01-16 00:00:00T21:30:00')",
        "status": "completed",
        "name": "Rohit Thomas",
        "mobile": "8984642891",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T1 KIAL",
        "dateTime": "new Date('2025-01-16 00:00:00T22:30:00')",
        "status": "completed",
        "name": "Bhavani",
        "mobile": "8335801579",
        "notes": "Drop Pet in Marathahalli. Take ORR TOLL-ROAD. Collect 725.",
        "driverName": "Muni Raju",
        "tripCost": 730
    },
    {
        "fromLocation": "Indiranagar",
        "toLocation": "T2 KIAL",
        "dateTime": "new Date('2025-01-17 00:00:00T02:00:00')",
        "status": "cancelled",
        "name": "Poojitha Ram",
        "mobile": "7760180306",
        "notes": "Delay in pick-up due to charging",
        "driverName": "Muni Raju",
        "tripCost": 0
    },
    {
        "fromLocation": "T1, KIAL",
        "toLocation": "PLH, Varthur",
        "dateTime": "new Date('2025-01-17 00:00:00T15:15:00')",
        "status": "completed",
        "name": "Dinesh Jain",
        "mobile": "9999662952",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 599
    },
    {
        "fromLocation": "Vaswani Bella Vista, Whitefield",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-17 00:00:00T15:45:00')",
        "status": "completed",
        "name": "Abhishek Kothari",
        "mobile": "9619633463",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 600
    },
    {
        "fromLocation": "T1 KIAL",
        "toLocation": "Sobha Carnation",
        "dateTime": "new Date('2025-01-17 00:00:00T20:00:00')",
        "status": "completed",
        "name": "Garima",
        "mobile": "9039742452",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 600
    },
    {
        "fromLocation": "T1, KIAL",
        "toLocation": "Suncity Apartment, Bellandur",
        "dateTime": "new Date('2025-01-17 00:00:00T23:00:00')",
        "status": "completed",
        "name": "Chaitanya Mittal",
        "mobile": "9582288062",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 730
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-18 00:00:00T13:00:00')",
        "status": "completed",
        "name": "Ashok Tuwani",
        "mobile": "9810022097",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-18 00:00:00T13:30:00')",
        "status": "completed",
        "name": "Pranesh Kumar",
        "mobile": "7200218689",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 600
    },
    {
        "fromLocation": "T1, KIAL",
        "toLocation": "Godrej Woodsman Estate, Hebbal",
        "dateTime": "new Date('2025-01-18 00:00:00T20:15:00')",
        "status": "cancelled",
        "name": "Rizwan",
        "mobile": "9961025666",
        "notes": "Reached wrong pick-up address",
        "driverName": "Muni Raju",
        "tripCost": 0
    },
    {
        "fromLocation": "T1 KIAL",
        "toLocation": "Mahaveer Maple, Kundanahalli",
        "dateTime": "new Date('2025-01-19 00:00:00T02:00:00')",
        "status": "completed",
        "name": "Abik Halder",
        "mobile": "7205487326",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 600
    },
    {
        "fromLocation": "Sattva Greenage, Bommanahalli",
        "toLocation": "T1 KIAL",
        "dateTime": "new Date('2025-01-19 00:00:00T06:45:00')",
        "status": "completed",
        "name": "Akash Doifode",
        "mobile": "9420911546",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 599
    },
    {
        "fromLocation": "T2 KIAL",
        "toLocation": "ND Passion Apartment, Haralur",
        "dateTime": "new Date('2025-01-19 00:00:00T08:00:00')",
        "status": "completed",
        "name": "Abik Halder",
        "mobile": "9432750536",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 599
    },
    {
        "fromLocation": "T1 KIAL",
        "toLocation": "PLH",
        "dateTime": "new Date('2025-01-19 00:00:00T08:00:00')",
        "status": "completed",
        "name": "Bhavani",
        "mobile": "8335801579",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 599
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T1 KIAL",
        "dateTime": "new Date('2025-01-19 00:00:00T08:30:00')",
        "status": "completed",
        "name": null,
        "mobile": "6392950015",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 599
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-19 00:00:00T10:00:00')",
        "status": "completed",
        "name": "Kamal",
        "mobile": "9811837749",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },
    {
        "fromLocation": "Brigade Cornerstone, Varthur",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-19 00:00:00T11:30:00')",
        "status": "completed",
        "name": "Nikhil Ghodke",
        "mobile": "8087272290",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 599
    },
    {
        "fromLocation": "SNN Raj Grandeur, Bommanahalli",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-19 00:00:00T15:30:00')",
        "status": "completed",
        "name": "Nikhil Agrawalla",
        "mobile": "9004330953",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 725
    },
    {
        "fromLocation": "T1, KIAL",
        "toLocation": "Kadubeesanahalli",
        "dateTime": "new Date('2025-01-19 00:00:00T15:00:00')",
        "status": "completed",
        "name": "Sudhanshu Rai",
        "mobile": "9721802777",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 599
    },
    {
        "fromLocation": "T1 KIAL",
        "toLocation": "PLH",
        "dateTime": "new Date('2025-01-19 00:00:00T17:00:00')",
        "status": "cancelled",
        "name": "Abhi",
        "mobile": "7006536816",
        "notes": "Flight Cancelled",
        "driverName": "Chandan Kumar",
        "tripCost": 0
    },


    {
        "fromLocation": "T1 KIAL",
        "toLocation": "Mahaveer Ranches",
        "dateTime": "new Date('2025-01-19 00:00:00T16:00:00')",
        "status": "Empty",
        "name": "Tarun",
        "mobile": "9818413183",
        "notes": "",
        "driverName": "BYD",
        "tripCost": 0
    },
    {
        "fromLocation": "Sobha Carnation, Bellandur",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-20 00:00:00T00:05:00')",
        "status": "completed",
        "name": "Garima",
        "mobile": "9039742452",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 600
    },
    {
        "fromLocation": "Purva Westend, Kudlu Gate",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-20 00:00:00T06:00:00')",
        "status": "completed",
        "name": "Vishal",
        "mobile": "9731383802",
        "notes": "Cash - offset",
        "driverName": "Muni Raju",
        "tripCost": 600
    },
    {
        "fromLocation": "Sattva Greenage, Bommanahalli",
        "toLocation": "T1 KIAL",
        "dateTime": "new Date('2025-01-20 00:00:00T16:00:00')",
        "status": "completed",
        "name": "Bharat Gupta",
        "mobile": "9899822183",
        "notes": "Through Toll-route",
        "driverName": "Jabed Laskar",
        "tripCost": 725
    },
    {
        "fromLocation": "T2 KIAL",
        "toLocation": "Bellandur",
        "dateTime": "new Date('2025-01-21 00:00:00T00:15:00')",
        "status": "completed",
        "name": "PD",
        "mobile": "9742241792",
        "notes": "699 + Toll",
        "driverName": "Muni Raju",
        "tripCost": 825
    },
    {
        "fromLocation": "T2, KIAL",
        "toLocation": "DKR Deepak's Abode, Kaggadaspura",
        "dateTime": "new Date('2025-01-21 00:00:00T02:30:00')",
        "status": "completed",
        "name": "Nadha Neelambra",
        "mobile": "7024628595",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },
    {
        "fromLocation": "GR Sunshine, Gunjur",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-21 00:00:00T03:00:00')",
        "status": "completed",
        "name": "Yogita",
        "mobile": "9380733739",
        "notes": "599+Toll",
        "driverName": "Muni Raju",
        "tripCost": 725
    },
    {
        "fromLocation": "Mahaveer Ranches, Hosa Road",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-21 00:00:00T13:00:00')",
        "status": "completed",
        "name": "Raja",
        "mobile": "6202954289",
        "notes": "Through Toll-route",
        "driverName": "Chandan Kumar",
        "tripCost": 725
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-21 00:00:00T14:00:00')",
        "status": "completed",
        "name": "Sola",
        "mobile": "9589041772",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Renaissance Rainbow Apartments, Brookefield",
        "dateTime": "new Date('2024-01-21 00:00:00T19:30:00')",
        "status": "completed",
        "name": "Vipin",
        "mobile": "9833717660",
        "notes": "Cash rcvd",
        "driverName": "Chandan Kumar",
        "tripCost": 600
    },
    {
        "fromLocation": "Shriram Spandhana, Varthur",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-22 00:00:00T01:00:00')",
        "status": "completed",
        "name": "Akhil S",
        "mobile": "9930216463",
        "notes": "via Toll route",
        "driverName": "Muni Raju",
        "tripCost": 725
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Sattva Greenage, Bommanahalli",
        "dateTime": "new Date('2025-01-22 00:00:00T01:30:00')",
        "status": "completed",
        "name": "Akash Doifode",
        "mobile": "9420911546",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 599
    },
    {
        "fromLocation": "Rohan Iksha Apartment, Bhoganahalli",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-22 00:00:00T03:30:00')",
        "status": "completed",
        "name": "Ankit G",
        "mobile": "9844811916",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 599
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-22 00:00:00T06:30:00')",
        "status": "cancelled",
        "name": "Aditi Sharma",
        "mobile": "8050576735",
        "notes": "Couldn't serve. Late due to charging issue.",
        "driverName": "Muni Raju",
        "tripCost": 0
    },
    {
        "fromLocation": "Purva Midtown, KR Puram",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-22 00:00:00T06:30:00')",
        "status": "completed",
        "name": "Apoorva Mishra",
        "mobile": "6387679687",
        "notes": "599+Toll",
        "driverName": "Chandan Kumar",
        "tripCost": 725
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-22 00:00:00T08:00:00')",
        "status": "completed",
        "name": "Divya Rani",
        "mobile": "8469510331",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },
    {
        "fromLocation": "T1 Airport",
        "toLocation": "PLH",
        "dateTime": "new Date('2025-01-22 00:00:00T16:00:00')",
        "status": "completed",
        "name": "Ashok Tuwani",
        "mobile": "9810022097",
        "notes": "Cash rcvd",
        "driverName": "Chandan Kumar",
        "tripCost": 600
    },
    {
        "fromLocation": "T2, Airport",
        "toLocation": "PLH",
        "dateTime": "new Date('2025-01-22 00:00:00T18:30:00')",
        "status": "completed",
        "name": "Gobind Tulsi",
        "mobile": "9650054068",
        "notes": "Cash rcvd",
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },
    {
        "fromLocation": "T2, KIAL",
        "toLocation": "Mahaveer Ranches, A5-1006",
        "dateTime": "new Date('2025-01-23 00:00:00T01:00:00')",
        "status": "completed",
        "name": "Nayanjyoti Bhagwati",
        "mobile": "9742165274",
        "notes": "699 (via no-toll route)",
        "driverName": "Jabed Laskar",
        "tripCost": 750
    },
    {
        "fromLocation": "RBD Stillwaters Apartment, Haralur",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-23 00:00:00T01:30:00')",
        "status": "completed",
        "name": "Varun",
        "mobile": "7771812000",
        "notes": "Toll",
        "driverName": "Chandan Kumar",
        "tripCost": 725
    },
    {
        "fromLocation": "Mahaveer Ranches, B1-1204",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-23 00:00:00T08:00:00')",
        "status": "completed",
        "name": "Anand A",
        "mobile": "9986304215",
        "notes": "Toll",
        "driverName": "Chandan Kumar",
        "tripCost": 725
    },
    {
        "fromLocation": "Hebbal",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-23 00:00:00T13:30:00')",
        "status": "completed",
        "name": "Mythili",
        "mobile": "9940671927",
        "notes": "Toll",
        "driverName": "Jabed Laskar",
        "tripCost": 725
    },
    {
        "fromLocation": "Prestige Sunrise Park, Birchwood",
        "toLocation": "T2, Airport",
        "dateTime": "new Date('2025-01-23 00:00:00T15:30:00')",
        "status": "completed",
        "name": "Sanjeev",
        "mobile": "9886081817",
        "notes": "825 (via Toll-road)",
        "driverName": "Chandan Kumar",
        "tripCost": 850
    },
    {
        "fromLocation": "T1 Airport",
        "toLocation": "Suncity, Bellandur",
        "dateTime": "new Date('2025-01-23 00:00:00T23:30:00')",
        "status": "completed",
        "name": "Kavita",
        "mobile": "8197674287",
        "notes": "Toll",
        "driverName": "Muni Raju",
        "tripCost": 825
    },
    {
        "fromLocation": "Hoodi Whitefield",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-24 00:00:00T01:00:00')",
        "status": "completed",
        "name": "Sumit Chauhan",
        "mobile": "7829851201",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-24 00:00:00T03:00:00')",
        "status": "Empty",
        "name": "Rakesh Ranjan",
        "mobile": "9764996383",
        "notes": "Tyre puncture",
        "driverName": "Muni Raju",
        "tripCost": 0
    },
    {
        "fromLocation": "Sattva Greenage, Bommanahalli",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-24 00:00:00T05:00:00')",
        "status": "completed",
        "name": "Snehil",
        "mobile": "7600070840",
        "notes": "Toll",
        "driverName": "Jabed Laskar",
        "tripCost": 725
    },
    {
        "fromLocation": "T1 Airport",
        "toLocation": "PLH",
        "dateTime": "new Date('2025-01-24 00:00:00T06:00:00')",
        "status": "Empty",
        "name": "Rakesh Ranjan",
        "mobile": "9764996383",
        "notes": "Tyre puncture",
        "driverName": "Muni Raju",
        "tripCost": 0
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T1 Airport",
        "dateTime": "new Date('2025-01-24 00:00:00T07:30:00')",
        "status": "completed",
        "name": "Umaid",
        "mobile": "9901455023",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 600
    },
    {
        "fromLocation": "Sattva Greenage, Bommanahalli",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-24 00:00:00T11:00:00')",
        "status": "completed",
        "name": "Shagun Vaish",
        "mobile": "9167029165",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 725
    },
    {
        "fromLocation": "Mahaveer Ranches, Hosa Road",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-24 00:00:00T15:00:00')",
        "status": "completed",
        "name": null,
        "mobile": "9886769156",
        "notes": "750 no-toll",
        "driverName": "Jabed Laskar",
        "tripCost": 750
    },
    {
        "fromLocation": "T2, Airport",
        "toLocation": "Salarpuria Greenage, Bommanahalli",
        "dateTime": "new Date('2025-01-24 00:00:00T21:45:00')",
        "status": "completed",
        "name": "Snehil",
        "mobile": "7600070840",
        "notes": "Toll",
        "driverName": "Muni Raju",
        "tripCost": 725
    },
    {
        "fromLocation": "SNN Raj Etternia, Haralur",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-25 00:00:00T01:30:00')",
        "status": "completed",
        "name": "Gaurav",
        "mobile": "8800377227",
        "notes": "699 no-toll",
        "driverName": "Bhagath",
        "tripCost": 825
    },
    {
        "fromLocation": "GR Sunshine, Carmelaram",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-25 00:00:00T02:00:00')",
        "status": "completed",
        "name": "Atul",
        "mobile": "9741296062",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 600
    },
    {
        "fromLocation": "Sangam Paradise, Marathahalli",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-25 00:00:00T03:00:00')",
        "status": "completed",
        "name": "Amit",
        "mobile": "9606777371",
        "notes": "Toll",
        "driverName": "Chandan Kumar",
        "tripCost": 725
    },
    {
        "fromLocation": "Habitat Eden Heights, Hoodi, Whitefield",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-25 00:00:00T05:30:00')",
        "status": "completed",
        "name": "SM",
        "mobile": "9755447306",
        "notes": "Cash - offset",
        "driverName": "Muni Raju",
        "tripCost": 600
    },
    {
        "fromLocation": null,
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-25 00:00:00T06:00:00')",
        "status": "completed",
        "name": "Chandan",
        "mobile": "7204727763",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 725
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-25 00:00:00T08:00:00')",
        "status": "completed",
        "name": "Harshika",
        "mobile": "8373970836",
        "notes": "Cash rcvd",
        "driverName": "Bhagath",
        "tripCost": 600
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "PLH",
        "dateTime": "new Date('2025-01-25 00:00:00T13:00:00')",
        "status": "Empty",
        "name": "Pranesh",
        "mobile": "7200218689",
        "notes": "",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Brigade Utopia, Varthur",
        "dateTime": "new Date('2025-01-25 00:00:00T15:00:00')",
        "status": "completed",
        "name": "Vineet Ranjan",
        "mobile": "8880893475",
        "notes": "Cash",
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },
    {
        "fromLocation": "Mahaveer Maple, Kundalahalli",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-26 00:00:00T03:15:00')",
        "status": "completed",
        "name": "Abik Halder",
        "mobile": "7205487326",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 600
    },
    {
        "fromLocation": "Nandi Citadel",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-26 00:00:00T05:00:00')",
        "status": "completed",
        "name": null,
        "mobile": "9940499007",
        "notes": "699 no-toll",
        "driverName": "Bhagath",
        "tripCost": 825
    },
    {
        "fromLocation": "T2, Airport",
        "toLocation": "Suncity, Bellandur",
        "dateTime": "new Date('2025-01-26 00:00:00T10:30:00')",
        "status": "completed",
        "name": "Dinesh",
        "mobile": "9871290102",
        "notes": "699 no-toll",
        "driverName": "Jabed Laskar",
        "tripCost": 700
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Mahaveer Ranches",
        "dateTime": "new Date('2025-01-26 00:00:00T15:00:00')",
        "status": "completed",
        "name": "Richa",
        "mobile": "9155524079",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 599
    },
    {
        "fromLocation": "T1 Airport",
        "toLocation": "Lisha Vistara, Bellandur",
        "dateTime": "new Date('2025-01-26 00:00:00T16:30:00')",
        "status": "completed",
        "name": "Kapil",
        "mobile": "9958872341",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 600
    },
    {
        "fromLocation": "T1 Airport",
        "toLocation": "Jaya Ficus",
        "dateTime": "new Date('2025-01-26 00:00:00T19:00:00')",
        "status": "Empty",
        "name": null,
        "mobile": "9836953996",
        "notes": "Unable to reach on time",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "T1 Airport",
        "toLocation": "PLH",
        "dateTime": "new Date('2025-01-26 00:00:00T20:00:00')",
        "status": "completed",
        "name": "Umaid",
        "mobile": "9901455023",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },



    {
        "fromLocation": "PLH, Varthur",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-27 00:00:00T05:30:00')",
        "status": "completed",
        "name": "Ashok Tuwani",
        "mobile": "9810022097",
        "notes": "Wrong payment",
        "driverName": "Bhagath",
        "tripCost": 0
    },
    {
        "fromLocation": "Zolo Maven PG",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-27 00:00:00T06:00:00')",
        "status": "completed",
        "name": "Vikash Kumar",
        "mobile": "7815088541",
        "notes": "Toll",
        "driverName": "Muni Raju",
        "tripCost": 725
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Mahaveer Maple",
        "dateTime": "new Date('2025-01-27 00:00:00T06:30:00')",
        "status": "completed",
        "name": "Abik Halder",
        "mobile": "7205487326",
        "notes": "",
        "driverName": "Bhagath",
        "tripCost": 600
    },
    {
        "fromLocation": "Mahaveer Ranches",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-27 00:00:00T07:30:00')",
        "status": "completed",
        "name": "Sakshi Rohilla",
        "mobile": "8136902522",
        "notes": "Double toll (230)",
        "driverName": "Chandan Kumar",
        "tripCost": 800
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": null,
        "dateTime": "new Date('2025-01-27 00:00:00T17:00:00')",
        "status": "completed",
        "name": "Chandan",
        "mobile": "7204727763",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 600
    },
    {
        "fromLocation": "Prestige Sunrise Park, Birchwood",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-27 00:00:00T18:30:00')",
        "status": "completed",
        "name": "Atul",
        "mobile": "9686581268",
        "notes": "925 (via toll)",
        "driverName": "Jabed Laskar",
        "tripCost": 925
    },
    {
        "fromLocation": "T2, Airport",
        "toLocation": "PLH",
        "dateTime": "new Date('2025-01-27 00:00:00T23:00:00')",
        "status": "completed",
        "name": "Kamal",
        "mobile": "9811837749",
        "notes": "Cash - with Jabed",
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },
    {
        "fromLocation": "T2, Airport",
        "toLocation": "Prestige Sunrise Park, Birchwood",
        "dateTime": "new Date('2025-01-28 00:00:00T01:15:00')",
        "status": "completed",
        "name": "Sanjeev",
        "mobile": "9886081817",
        "notes": "825 (via Toll-road)",
        "driverName": "Muni Raju",
        "tripCost": 825
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T2, Airport",
        "dateTime": "new Date('2025-01-28 00:00:00T4.15 AM')",
        "status": "completed",
        "name": "Megha",
        "mobile": "9958230059",
        "notes": 699,
        "driverName": "Bhagath",
        "tripCost": 699
    },
    {
        "fromLocation": "T1, KIAL",
        "toLocation": "Bagmane Tech Park",
        "dateTime": "new Date('2025-01-28 00:00:00T11:00:00')",
        "status": "completed",
        "name": "Mayur Jadhav",
        "mobile": "9403583749",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 725
    },
    {
        "fromLocation": "Mahaveer Ranches",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-28 00:00:00T11:30:00')",
        "status": "completed",
        "name": "VB",
        "mobile": "7829765560",
        "notes": "Cah - with Jabed",
        "driverName": "Jabed Laskar",
        "tripCost": 725
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-28 00:00:00T13:00:00')",
        "status": "completed",
        "name": "Kasa Kotaiah",
        "mobile": "8790494449",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 600
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Indiranagar",
        "dateTime": "new Date('2025-01-28 00:00:00T13:30:00')",
        "status": "Scheduled",
        "name": "Ravi Kannan",
        "mobile": "9916586821",
        "notes": "Unable to serve due to traffic\/scheduling",
        "driverName": "Jabed Laskar",
        "tripCost": 0
    },
    {
        "fromLocation": "PLH, Varthur",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-29 00:00:00T01:45:00')",
        "status": "completed",
        "name": "Sujit",
        "mobile": "9871575420",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 700
    },
    {
        "fromLocation": "PLH",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-29 00:00:00T04:00:00')",
        "status": "completed",
        "name": "Umaid Shafeeq",
        "mobile": "9901455023",
        "notes": "",
        "driverName": "Bhagath",
        "tripCost": 725
    },
    {
        "fromLocation": "Mahaveer Ranches",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-29 00:00:00T04:00:00')",
        "status": "completed",
        "name": "Dristiron",
        "mobile": "9387701995",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 825
    },
    {
        "fromLocation": "SJR Palazza City, Sarjapur Road",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-29 00:00:00T11:00:00')",
        "status": "Empty",
        "name": "Andy",
        "mobile": "8553012909",
        "notes": "",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "Purvi Symphony, Varthur",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-29 00:00:00T11:00:00')",
        "status": "Empty",
        "name": "Andy",
        "mobile": "8553012909",
        "notes": "",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "PLH (Opposite), Varthur",
        "dateTime": "new Date('2025-01-29 00:00:00T16:00:00')",
        "status": "Empty",
        "name": "Tarun",
        "mobile": "8108110812",
        "notes": "",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "T1, KIAL",
        "toLocation": "PLH, Varthur",
        "dateTime": "new Date('2025-01-29 00:00:00T9.45 PM')",
        "status": "completed",
        "name": "Megha",
        "mobile": "9958230059",
        "notes": 699,
        "driverName": "Jabed Laskar",
        "tripCost": 699
    },
    {
        "fromLocation": "PLH, Varthur",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-01-30 00:00:00T08:45:00')",
        "status": "cancelled",
        "name": "Indrasish Saha",
        "mobile": "8860879513",
        "notes": "",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "Prestige Ferns Residency, Haralur",
        "toLocation": "T2, Airport",
        "dateTime": "new Date('2025-01-30 00:00:00T15:00:00')",
        "status": "completed",
        "name": "Siddhant",
        "mobile": "7869891880",
        "notes": 699,
        "driverName": "Jabed Laskar",
        "tripCost": 700
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Mahaveer Ranches",
        "dateTime": "new Date('2025-01-30 00:00:00T14:30:00')",
        "status": "Empty",
        "name": "Anand",
        "mobile": "9986304215",
        "notes": "",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "PLH, Varthur",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-30 00:00:00T15:30:00')",
        "status": "cancelled",
        "name": "Ashray Sudhir",
        "mobile": "8369160695",
        "notes": "",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "PWC Bagmane, Indiranagar",
        "toLocation": "T2, Airport",
        "dateTime": "new Date('2025-01-30 00:00:00T16:00:00')",
        "status": "completed",
        "name": "Mayur Jadhav",
        "mobile": "9403583749",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 725
    },
    {
        "fromLocation": "SJR Palazza City, Sarjapur Road",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-31 00:00:00T06:30:00')",
        "status": "Scheduled",
        "name": "Prabita",
        "mobile": "8310089398",
        "notes": "Cash with Bhagath",
        "driverName": "Bhagath",
        "tripCost": 600
    },
    {
        "fromLocation": "Sree Aditya Elite, Whitefield ",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-31 00:00:00T08:30:00')",
        "status": "completed",
        "name": "Praveen",
        "mobile": "9555767736",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 599
    },
    {
        "fromLocation": "Sree Aditya Elite, Whitefield ",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-31 00:00:00T08:30:00')",
        "status": "completed",
        "name": "Praveen",
        "mobile": "9555767736",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 599
    },
    {
        "fromLocation": "Suncity, Bellandur",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-01-31 00:00:00T18:30:00')",
        "status": "Scheduled",
        "name": "Chaitanya",
        "mobile": "9582288062",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 720
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Sobha Dream Acres, Varthur",
        "dateTime": "new Date('2025-02-01 00:00:00T00:30:00')",
        "status": "Scheduled",
        "name": "Amit Jain",
        "mobile": "8108666926",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },
    {
        "fromLocation": "Kalyan Nagar",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-01 00:00:00T01:00:00')",
        "status": "Scheduled",
        "name": "Harshit Harsh",
        "mobile": "8582977159",
        "notes": "Wrong pick-up address",
        "driverName": "Muni Raju",
        "tripCost": 0
    },
    {
        "fromLocation": "T2, Airport",
        "toLocation": "Sangam Paradise, Marathahalli",
        "dateTime": "new Date('2025-02-01 00:00:00T19:00:00')",
        "status": "Scheduled",
        "name": "Amit",
        "mobile": "9606777371",
        "notes": "",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "Jeevan Samskruthi Apartment, Munnekollal",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-02 00:00:00T10:30:00')",
        "status": "Empty",
        "name": "Bharath Kumar K",
        "mobile": "8050588124",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },
    {
        "fromLocation": "Ranka Apartment, Bannerghata Road",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-02 00:00:00T14:30:00')",
        "status": "Empty",
        "name": "Vipul",
        "mobile": "9770171920",
        "notes": "",
        "driverName": "Chandan Kumar",
        "tripCost": 699
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Sobha Magnolia",
        "dateTime": "new Date('2025-02-02 00:00:00T22:00:00')",
        "status": "Empty",
        "name": "Niloy",
        "mobile": "9752090488",
        "notes": "699 - no-toll",
        "driverName": "Bhagath",
        "tripCost": 825
    },
    {
        "fromLocation": "Salarpuria Greenage, Bommanahalli",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-03 00:00:00T02:15:00')",
        "status": "completed",
        "name": "Snehil",
        "mobile": "7600070840",
        "notes": 599,
        "driverName": "Bhagath",
        "tripCost": 725
    },
    {
        "fromLocation": "Lisha Vistara, Bellandur",
        "toLocation": "T2, Airport",
        "dateTime": "new Date('2025-02-03 00:00:00T04:15:00')",
        "status": "completed",
        "name": null,
        "mobile": "9958872341",
        "notes": 599,
        "driverName": "Muni Raju",
        "tripCost": 600
    },
    {
        "fromLocation": "Springfield Apartment, Bellandur",
        "toLocation": "T2, Airport",
        "dateTime": "new Date('2025-02-03 00:00:00T07:30:00')",
        "status": "completed",
        "name": "Rahul Bansal",
        "mobile": "9901999200",
        "notes": 699,
        "driverName": "Bhagath",
        "tripCost": 825
    },
    {
        "fromLocation": "Brigade Parkside East, Sarjapur Road",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-03 00:00:00T15:00:00')",
        "status": "completed",
        "name": "Nippun",
        "mobile": "8600096662",
        "notes": 599,
        "driverName": "Chandan Kumar",
        "tripCost": 725
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "PLH, Varthur",
        "dateTime": "new Date('2025-02-03 00:00:00T16:15:00')",
        "status": "completed",
        "name": "Sunny",
        "mobile": "9773535208",
        "notes": 599,
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },
    {
        "fromLocation": "T1 Airport",
        "toLocation": "PLH, Varthur",
        "dateTime": "new Date('2025-02-03 00:00:00T17:00:00')",
        "status": "completed",
        "name": "Sonali",
        "mobile": "9650418565",
        "notes": 699,
        "driverName": "Chandan Kumar",
        "tripCost": 750
    },
    {
        "fromLocation": "Sobha Dream Acres, Balagere",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-03 00:00:00T17:00:00')",
        "status": "completed",
        "name": "Amit Jain",
        "mobile": "8108666926",
        "notes": "",
        "driverName": "Bhagath",
        "tripCost": 0
    },
    {
        "fromLocation": "PLH, Varthur",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-03 00:00:00T17:00:00')",
        "status": "completed",
        "name": "Vinod Jain",
        "mobile": "8660137295",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 700
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "PLH, Varthur",
        "dateTime": "new Date('2025-02-03 00:00:00T19:00:00')",
        "status": "completed",
        "name": "Vinod Jain",
        "mobile": "8660137295",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 700
    },
    {
        "fromLocation": "KR Puram",
        "toLocation": "T2 Airport",
        "dateTime": "new Date('2025-02-03 00:00:00T20:00:00')",
        "status": "completed",
        "name": "Anantha",
        "mobile": "9740955882",
        "notes": "",
        "driverName": "Jabed Laskar",
        "tripCost": 699
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "PLH, Varthur",
        "dateTime": "new Date('2025-02-04 00:00:00T02:30:00')",
        "status": "completed",
        "name": "Vaibhav",
        "mobile": "8950808939",
        "notes": "",
        "driverName": "Bhagath",
        "tripCost": 700
    },
    {
        "fromLocation": "Hoodi Circle",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-04 00:00:00T11:00:00')",
        "status": "completed",
        "name": "Eiya",
        "mobile": "6001054931",
        "notes": "Cash - with Jabed",
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Rove Inn, Jalahalli",
        "dateTime": "new Date('2025-02-04 00:00:00T12:15:00')",
        "status": "Empty",
        "name": "Sunny",
        "mobile": "9773535208",
        "notes": 599,
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "Brigade Utopia, Varthur",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-04 00:00:00T14:30:00')",
        "status": "completed",
        "name": "Nikhil Ghodke",
        "mobile": "8087272290",
        "notes": 599,
        "driverName": "Jabed Laskar",
        "tripCost": 599
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Suncity Apartment, Bellandur",
        "dateTime": "new Date('2025-02-04 00:00:00T17:00:00')",
        "status": "completed",
        "name": "Shubham Mantri",
        "mobile": "9163131886",
        "notes": "Cash - with Jabed",
        "driverName": "Jabed Laskar",
        "tripCost": 700
    },
    {
        "fromLocation": "PLH, Varthur",
        "toLocation": "Whitefield Railway Station",
        "dateTime": "new Date('2025-02-04 00:00:00T20:30:00')",
        "status": "completed",
        "name": "Dinesh",
        "mobile": "9999662952",
        "notes": 350,
        "driverName": "Muni Raju",
        "tripCost": 0
    },
    {
        "fromLocation": "PLH, Varthur",
        "toLocation": "Whitefield Railway Station",
        "dateTime": "new Date('2025-02-04 00:00:00T20:30:00')",
        "status": "completed",
        "name": "Dinesh",
        "mobile": "9999662952",
        "notes": 350,
        "driverName": "Jabed Laskar",
        "tripCost": 350
    },
    {
        "fromLocation": "CANDEUR SIGNATURE",
        "toLocation": "Whitefield Railway Station",
        "dateTime": "new Date('2025-02-04 00:00:00T20:30:00')",
        "status": "completed",
        "name": "Kiran Patel",
        "mobile": "9302102690",
        "notes": 350,
        "driverName": "Bhagath",
        "tripCost": 0
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Jeevan Samskruthi Apartment, Munnekollal",
        "dateTime": "new Date('2025-02-04 00:00:00T23:00:00')",
        "status": "completed",
        "name": "Bharath Kumar K",
        "mobile": "8050588124",
        "notes": 699,
        "driverName": "Muni Raju",
        "tripCost": 700
    },
    {
        "fromLocation": "T2, Airport",
        "toLocation": "PLH",
        "dateTime": "new Date('2025-02-04 00:00:00T23:00:00')",
        "status": "completed",
        "name": "Sujit",
        "mobile": "9871575420",
        "notes": 699,
        "driverName": "Bhagath",
        "tripCost": 700
    },
    {
        "fromLocation": "Mahaveer Ranches, Hosa Road",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-05 00:00:00T03:10:00')",
        "status": "completed",
        "name": "Manish Khede",
        "mobile": "8827405287",
        "notes": "799 - no-toll",
        "driverName": "Bhagath",
        "tripCost": 925
    },
    {
        "fromLocation": "PLH, Varthur",
        "toLocation": "T2, Airport",
        "dateTime": "new Date('2025-02-05 00:00:00T04:00:00')",
        "status": "completed",
        "name": "Advit",
        "mobile": "9972610674",
        "notes": 599,
        "driverName": "Muni Raju",
        "tripCost": 599
    },
    {
        "fromLocation": "Brigade Utopia, Varthur",
        "toLocation": "T2, Airport",
        "dateTime": "new Date('2025-02-05 00:00:00T09:00:00')",
        "status": "completed",
        "name": "Vineet Ranjan",
        "mobile": "8880893475",
        "notes": 599,
        "driverName": "Jabed Laskar",
        "tripCost": 599
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Rove Inn, Jalahalli",
        "dateTime": "new Date('2025-02-05 00:00:00T11:00:00')",
        "status": "Empty",
        "name": "Sunny",
        "mobile": "9773535208",
        "notes": "Flight rescheduled",
        "driverName": "Jabed Laskar",
        "tripCost": 0
    },
    {
        "fromLocation": "T2, Airport",
        "toLocation": "PLH, Varthur",
        "dateTime": "new Date('2025-02-05 00:00:00T13:30:00')",
        "status": "completed",
        "name": "Kamal",
        "mobile": "9811837749",
        "notes": 599,
        "driverName": "Jabed Laskar",
        "tripCost": 600
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Salarpuria Greenage, Bommanahalli",
        "dateTime": "new Date('2025-02-05 00:00:00T21:00:00')",
        "status": "completed",
        "name": "Snehil",
        "mobile": "7600070840",
        "notes": 599,
        "driverName": "Muni Raju",
        "tripCost": 725
    },
    {
        "fromLocation": "T2, Airport",
        "toLocation": "PLH, hobli",
        "dateTime": "new Date('2025-02-05 00:00:00T21:45:00')",
        "status": "Scheduled",
        "name": "Advit",
        "mobile": "9972610674",
        "notes": "No-show",
        "driverName": "Bhagath",
        "tripCost": 0
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "SJR Pallaza",
        "dateTime": "new Date('2025-02-06 00:00:00T00:05:00')",
        "status": "completed",
        "name": "Andy",
        "mobile": "8553012909",
        "notes": 699,
        "driverName": "Bhagath",
        "tripCost": 700
    },
    {
        "fromLocation": "Parimala Trinity",
        "toLocation": "T1 Airport",
        "dateTime": "new Date('2025-02-06 00:00:00T02:00:00')",
        "status": "completed",
        "name": "Sanu",
        "mobile": "8238918597",
        "notes": 699,
        "driverName": "Muni Raju",
        "tripCost": 700
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Salarpuria Greenage, Bommanahalli",
        "dateTime": "new Date('2025-02-06 00:00:00T07:30:00')",
        "status": "completed",
        "name": "Shagun Vaish",
        "mobile": "9167029165",
        "notes": 699,
        "driverName": "Bhagath",
        "tripCost": 725
    },
    {
        "fromLocation": "MSR Primerose Apartment",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-06 00:00:00T07:30:00')",
        "status": "completed",
        "name": "Ayush Saraf",
        "mobile": "9062167819",
        "notes": 699,
        "driverName": "Muni Raju",
        "tripCost": 700
    },
    {
        "fromLocation": "Salarpuria Greenage, Bommanahalli",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-06 00:00:00T20:00:00')",
        "status": "completed",
        "name": "Snehil",
        "mobile": "7600070840",
        "notes": 699,
        "driverName": "Bhagath",
        "tripCost": 825
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Pyramid Temple Bells, RR Nagar",
        "dateTime": "new Date('2025-02-06 00:00:00T22:30:00')",
        "status": "completed",
        "name": null,
        "mobile": "9886661345",
        "notes": 699,
        "driverName": "Bhagath",
        "tripCost": 825
    },
    {
        "fromLocation": "Purva Westend",
        "toLocation": "T1, KIAL",
        "dateTime": "new Date('2025-02-07 00:00:00T03:45:00')",
        "status": "completed",
        "name": "Saurav Chhabra",
        "mobile": "8764195520",
        "notes": 699,
        "driverName": "Bhagath",
        "tripCost": 825
    },
    {
        "fromLocation": "Karun Tummy, Electronic City",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-07 00:00:00T04:00:00')",
        "status": "completed",
        "name": "Rohit Kumar",
        "mobile": "7992350275",
        "notes": 699,
        "driverName": "Muni Raju",
        "tripCost": 825
    },
    {
        "fromLocation": "Sobha Habitech",
        "toLocation": "T2, Airport",
        "dateTime": "new Date('2025-02-07 00:00:00T15:00:00')",
        "status": "Scheduled",
        "name": "Mukul",
        "mobile": "8864807869",
        "notes": 699,
        "driverName": "Jabed Laskar",
        "tripCost": 0
    },
    {
        "fromLocation": "PLH, Varthur",
        "toLocation": "T2, Airport",
        "dateTime": "new Date('2025-02-07 00:00:00T18:00:00')",
        "status": "Scheduled",
        "name": "Abhishek",
        "mobile": "8586801947",
        "notes": 699,
        "driverName": "Bhagath",
        "tripCost": 0
    },
    {
        "fromLocation": "Bangalore International Exhibition Center",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-07 00:00:00T18:45:00')",
        "status": "Scheduled",
        "name": "Sunny",
        "mobile": "9773535208",
        "notes": 599,
        "driverName": "Jabed Laskar",
        "tripCost": 0
    },
    {
        "fromLocation": "Bangalore International Exhibition Center",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-07 00:00:00T18:45:00')",
        "status": "Empty",
        "name": "Sunny",
        "mobile": "9773535208",
        "notes": "Couldn't serve",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "T2, Airport",
        "toLocation": "GK Golden City, Kudlu Gate",
        "dateTime": "new Date('2025-02-07 00:00:00T19:30:00')",
        "status": "Scheduled",
        "name": "Ashvin Geete",
        "mobile": "9428573450",
        "notes": "799 - no-toll",
        "driverName": "Bhagath",
        "tripCost": 0
    },
    {
        "fromLocation": "PLH, Varthur",
        "toLocation": "T2, Airport",
        "dateTime": "new Date('2025-02-07 00:00:00T21:00:00')",
        "status": "Scheduled",
        "name": "Nidhi",
        "mobile": "9986504427",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 0
    },
    {
        "fromLocation": "Skanda Sukriti, Kadubisanahalli (Bellandur)",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-08 00:00:00T02:00:00')",
        "status": "Empty",
        "name": "Bhuvan Gaba",
        "mobile": "9355124105",
        "notes": "",
        "driverName": "Muni Raju",
        "tripCost": 0
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Diamond District, Domlur",
        "dateTime": "new Date('2025-02-08 00:00:00T09:15:00')",
        "status": "Empty",
        "name": "Tasneem Doola",
        "mobile": "9408745221",
        "notes": "",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "T2, Airport",
        "toLocation": "Mahaveer Ranches, Hosa Road",
        "dateTime": "new Date('2025-02-09 00:00:00T00:30:00')",
        "status": "Empty",
        "name": "Manish Khede",
        "mobile": "8827405287",
        "notes": "799 - no-toll",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "T1, Airport",
        "toLocation": "Skanda Sukriti, Kadubisanahalli (Bellandur)",
        "dateTime": "new Date('2025-02-09 00:00:00T22:30:00')",
        "status": "Empty",
        "name": "Bhuvan Gaba",
        "mobile": "9355124105",
        "notes": "",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "PLH, Varthur",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-10 00:00:00T08:30:00')",
        "status": "Empty",
        "name": "Satish Mathur",
        "mobile": "9591994472",
        "notes": 699.0,
        "driverName": "",
        "tripCost": 0
    },
    {
        "fromLocation": "PLH, Varthur",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-12 00:00:00T05:30:00')",
        "status": "Empty",
        "name": "Ashok Tuwani",
        "mobile": "9810022097",
        "notes": "",
        "driverName": "Empty",
        "tripCost": 0
    },
    {
        "fromLocation": "Suvastu Serene Hosa Road",
        "toLocation": "T1, Airport",
        "dateTime": "new Date('2025-02-24 00:00:00T13:30:00')",
        "status": "Empty",
        "name": "Shubhith",
        "mobile": "9407683662",
        "notes": 799,
        "driverName": "Empty",
        "tripCost": 0
    }
]

const bookings = [];
const getRandomDate = (start, end) => {
    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
};

const addRandomBookings = (numBookings) => {
    const bookings = [];
    const now = new Date();
    const end = new Date(now.getTime() + 48 * 60 * 60 * 1000); // 48 hours from now

    for (let i = 0; i < numBookings; i++) {
        const randomDate = getRandomDate(now, end);
        bookings.push({
            fromLocation: 'Random Location ' + (i + 1),
            toLocation: 'Destination ' + (i + 1),
            dateTime: randomDate,
            status: 'completed',
            name: 'Random User ' + (i + 1),
            mobile: '123456789' + i,
            notes: '',
            driverName: 'Random Driver',
            tripCost: Math.floor(Math.random() * 1000) + 100, // Random cost between 100 and 1100
        });
    }
    return bookings;
};

// Add 15 random bookings
const randomBookings = addRandomBookings(15);
bookings.push(...randomBookings); // Add random bookings to the existing bookings array

mongoose.connect(config.mongoose.url, config.mongoose.options)
    .then(async () => {
        console.log('Connected to MongoDB');
        await Booking.insertMany(bookings);
        console.log('Bookings inserted successfully');
        mongoose.connection.close();
    })
    .catch((error) => {
        console.error('Error connecting to MongoDB:', error);
    }); 